# Generated by Django 3.2.6 on 2021-08-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox')], max_length=200),
        ),
    ]
