# Generated by Django 3.2.6 on 2021-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('SELECT', 'select'), ('RADIO', 'radio'), ('CHECKBOX', 'checkbox')], max_length=200),
        ),
    ]
