# Generated by Django 3.2.6 on 2021-08-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_surveyresponse_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionResponse',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
